name: dask-mpi-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - dask>=2.0
  - distributed>=2.0
  - mpich
  - mpi4py
  - pytest
  - pytest-icdiff
  - pytest-cov
  - coverage
  - requests
  - codecov
  - jupyter-server-proxy
  - click
