name: dask-mpi-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - dask>=2.2
  - mpich
  - mpi4py
  - pytest
  - pytest-icdiff
  - pytest-cov
  - coverage
  - requests
  - codecov
  - jupyter-server-proxy
  - flake8
  - black
