name: dask-mpi-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - dask>=2.0
  - distributed>=2.0
  - openmpi
  - mpi4py
  - pytest
  - pytest-icdiff
  - pytest-cov
  - coverage
  - requests
  - codecov
