name: dask-mpi-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - dask
  - distributed
  - mpich
  - mpi4py
  - pytest
  - pytest-cov
  - coverage
  - requests
  - codecov
  - subprocess32


